base_url = "https://mitch.cx"

compile_sass = true
build_search_index = false

title = "Mitchell Nuckols"
author = "Mitchell Nuckols"
description = "Mitchell Nuckols is a embedded systems software and hardware developer based in San Diego, California"

[markdown]
highlight_code = true

[extra]
